import type {MapDefinition} from "../types/mapData.ts";
import {
    loadDutyPharmacies,
    loadAllPharmacies,
    loadEmergencyAssemblyPoints,
    loadFamilyHealthCenters,
    loadHighSchools,
    loadHospitals,
    loadKindergartens,
    loadMarketPlaces,
    loadMunicipalServicePoints,
    loadParkingPoints,
    loadUniversities,
    loadVeterinaryClinics,
    loadWifiPoints,
    loadTaxiStands,
    loadTrainStations,
    loadFerryPorts,
    loadMuhtarliklar,
    loadBeaches,
    loadBaths,
    loadSpringResorts,
    loadFairs,
    loadLibraries,
    loadCulturalCenters,
    loadOperaAndBallet,
    loadGalleriesAndHalls,
    loadPhilharmonic,
    loadCinemas,
    loadTheaters,
    loadMuseums,
    loadAncientCities,
    loadAncientCityStructures,
    loadMansionsAndManors,
    loadTowersMonumentsStatues,
    loadHistoricMarketAndCaravansaries,
    loadHistoricWaterStructures,
    loadHistoricStructures,
} from "../services/mapDataLoaders.ts";

export const mapRegistry: MapDefinition[] = [
    {
        id: 'nobetci-eczaneler',
        title: 'Nöbetçi Eczaneler',
        category: 'Sağlık',
        description: 'İzmir genelindeki güncel nöbetçi eczaneleri harita ve liste görünümüyle keşfedin.',
        searchPlaceholder: 'Eczane veya bölge ara...',
        emptyStateTitle: 'Eczane bulunamadı',
        emptyStateDescription: 'Arama terimini temizleyip tekrar deneyin.',
        sourceLabel: 'İzmir Açık Veri Portalı • Nöbetçi Eczaneler',
        sourceUrl: 'https://acikveri.bizizmir.com/dataset/nobetci-eczaneler-ve-eczane-listesi',
        loadPoints: loadDutyPharmacies,
    },
    {
        id: 'eczaneler',
        title: 'Tüm Eczaneler',
        category: 'Sağlık',
        description: 'İzmir genelindeki tüm eczaneleri harita üzerinde görüntüleyin ve iletişim bilgilerini alın.',
        searchPlaceholder: 'Eczane adı veya bölge ara...',
        emptyStateTitle: 'Eczane bulunamadı',
        emptyStateDescription: 'Arama terimini değiştirip tekrar deneyin.',
        sourceLabel: 'İzmir Açık Veri Portalı • Tüm Eczaneler',
        sourceUrl: 'https://acikveri.bizizmir.com/dataset/eczaneler-listesi',
        loadPoints: loadAllPharmacies,
    },
    {
        id: 'otoparklar',
        title: 'Otoparklar',
        category: 'Ulaşım',
        description: 'Otopark konumlarını ve doluluk bilgisini canlı olarak harita üzerinde görüntüleyin.',
        searchPlaceholder: 'Otopark veya işletmeci ara...',
        emptyStateTitle: 'Otopark bulunamadı',
        emptyStateDescription: 'Başka bir arama terimi deneyin.',
        sourceLabel: 'İzmir Açık Veri Portalı • Otopark Doluluk ve Lokasyon',
        sourceUrl: 'https://acikveri.bizizmir.com/dataset/otopark-doluluk-ve-lokasyon-bilgileri',
        loadPoints: loadParkingPoints,
    },
    {
        id: 'wizmirnet',
        title: 'WiZmirNET Noktaları',
        category: 'Dijital Hizmetler',
        description: 'Ücretsiz kablosuz internet noktalarını harita üzerinde görün ve yol tarifi alın.',
        searchPlaceholder: 'İlçe, mahalle veya nokta ara...',
        emptyStateTitle: 'WiZmirNET noktası bulunamadı',
        emptyStateDescription: 'Arama filtresini değiştirip tekrar deneyin.',
        sourceLabel: 'İzmir Açık Veri Portalı • Kablosuz İnternet Bağlantı Noktaları',
        sourceUrl: 'https://acikveri.bizizmir.com/dataset/kablosuz-internet-baglanti-noktalari',
        loadPoints: loadWifiPoints,
    },
    {
        id: 'afet-toplanma-alanlari',
        title: 'Afet Toplanma Alanları',
        category: 'Afet',
        description: 'Afet ve acil durum toplanma alanlarını ilçe ve mahalle bazında harita üzerinde görün.',
        searchPlaceholder: 'İlçe, mahalle veya toplanma alanı ara...',
        emptyStateTitle: 'Toplanma alanı bulunamadı',
        emptyStateDescription: 'Arama kriterini değiştirip tekrar deneyin.',
        sourceLabel: 'İzmir Açık Veri Portalı • Afet ve Acil Durum Toplanma Alanları',
        sourceUrl: 'https://acikveri.bizizmir.com/dataset/afet-ve-acil-durum-toplanma-alanlari',
        loadPoints: loadEmergencyAssemblyPoints,
    },
    {
        id: 'semt-pazarlari',
        title: 'Semt Pazarları',
        category: 'Yaşam',
        description: 'İzmir’deki semt pazarlarının konumlarını ve mahalle bazlı dağılımını keşfedin.',
        searchPlaceholder: 'Pazar yeri, ilçe veya mahalle ara...',
        emptyStateTitle: 'Pazar yeri bulunamadı',
        emptyStateDescription: 'Başka bir anahtar kelime ile yeniden arayın.',
        sourceLabel: 'İzmir Açık Veri Portalı • Semt Pazar Yerleri',
        sourceUrl: 'https://acikveri.bizizmir.com/dataset/semt-pazar-yerleri',
        loadPoints: loadMarketPlaces,
    },
    {
        id: 'izbb-hizmet-noktalari',
        title: 'İzBB Hizmet Noktaları',
        category: 'Belediye',
        description: 'Belediyeye bağlı hizmet noktalarını tek ekranda görün ve yol tarifi alın.',
        searchPlaceholder: 'Hizmet noktası, ilçe veya mahalle ara...',
        emptyStateTitle: 'Hizmet noktası bulunamadı',
        emptyStateDescription: 'Aramayı temizleyip tekrar deneyin.',
        sourceLabel: 'İzmir Açık Veri Portalı • İzBB Hizmet Noktaları',
        sourceUrl: 'https://acikveri.bizizmir.com/dataset/izbb-hizmet-noktalari',
        loadPoints: loadMunicipalServicePoints,
    },
    {
        id: 'hastaneler',
        title: 'Hastaneler',
        category: 'Sağlık',
        description: 'İzmir’deki hastanelerin konumlarını hızlıca görüntüleyin.',
        searchPlaceholder: 'Hastane, ilçe veya mahalle ara...',
        emptyStateTitle: 'Hastane bulunamadı',
        emptyStateDescription: 'Farklı bir arama terimi deneyin.',
        sourceLabel: 'İzmir Açık Veri Portalı • Hastaneler',
        sourceUrl: 'https://openapi.izmir.bel.tr/api/ibb/cbs/hastaneler',
        loadPoints: loadHospitals,
    },
    {
        id: 'aile-sagligi-merkezleri',
        title: 'Aile Sağlığı Merkezleri',
        category: 'Sağlık',
        description: 'Aile sağlığı merkezlerinin konumlarını ilçe ve mahalle bazında inceleyin.',
        searchPlaceholder: 'ASM, ilçe veya mahalle ara...',
        emptyStateTitle: 'Aile sağlığı merkezi bulunamadı',
        emptyStateDescription: 'Arama filtresini değiştirip tekrar deneyin.',
        sourceLabel: 'İzmir Açık Veri Portalı • Aile Sağlığı Merkezleri',
        sourceUrl: 'https://openapi.izmir.bel.tr/api/ibb/cbs/ailesagligimerkezleri',
        loadPoints: loadFamilyHealthCenters,
    },
    {
        id: 'veterinerlikler',
        title: 'Veterinerlikler',
        category: 'Sağlık',
        description: 'Veteriner kliniklerini ve mahalle bazlı dağılımını haritada görün.',
        searchPlaceholder: 'Veteriner, ilçe veya mahalle ara...',
        emptyStateTitle: 'Veterinerlik bulunamadı',
        emptyStateDescription: 'Başka bir arama terimi deneyin.',
        sourceLabel: 'İzmir Açık Veri Portalı • Veterinerlikler',
        sourceUrl: 'https://openapi.izmir.bel.tr/api/ibb/cbs/veterinerlikler',
        loadPoints: loadVeterinaryClinics,
    },
    {
        id: 'universiteler',
        title: 'Üniversiteler',
        category: 'Eğitim',
        description: 'İzmir’deki üniversiteleri ve kampüs lokasyonlarını görüntüleyin.',
        searchPlaceholder: 'Üniversite, ilçe veya mahalle ara...',
        emptyStateTitle: 'Üniversite bulunamadı',
        emptyStateDescription: 'Arama terimini güncelleyip yeniden deneyin.',
        sourceLabel: 'İzmir Açık Veri Portalı • Üniversiteler',
        sourceUrl: 'https://openapi.izmir.bel.tr/api/ibb/cbs/universiteler',
        loadPoints: loadUniversities,
    },
    {
        id: 'liseler',
        title: 'Liseler',
        category: 'Eğitim',
        description: 'İzmir genelindeki lise konumlarını harita ve liste olarak görün.',
        searchPlaceholder: 'Lise, ilçe veya mahalle ara...',
        emptyStateTitle: 'Lise bulunamadı',
        emptyStateDescription: 'Farklı bir arama terimi deneyin.',
        sourceLabel: 'İzmir Açık Veri Portalı • Liseler',
        sourceUrl: 'https://openapi.izmir.bel.tr/api/ibb/cbs/liseler',
        loadPoints: loadHighSchools,
    },
    {
        id: 'anaokullari',
        title: 'Anaokulları',
        category: 'Eğitim',
        description: 'Anaokulu konumlarını ilçe ve mahalle bazında keşfedin.',
        searchPlaceholder: 'Anaokulu, ilçe veya mahalle ara...',
        emptyStateTitle: 'Anaokulu bulunamadı',
        emptyStateDescription: 'Arama terimini temizleyip tekrar deneyin.',
        sourceLabel: 'İzmir Açık Veri Portalı • Anaokulları',
        sourceUrl: 'https://openapi.izmir.bel.tr/api/ibb/cbs/anaokullari',
        loadPoints: loadKindergartens,
    },
    {
        id: 'taksi-duraklar',
        title: 'Taksi Duraklari',
        category: 'Ulaşım',
        description: 'İzmir genelindeki taksi durakların konumlarını harita üzerinde görüntüleyin.',
        searchPlaceholder: 'Taksi duragi, ilçe veya mahalle ara...',
        emptyStateTitle: 'Taksi duragi bulunamadi',
        emptyStateDescription: 'Arama terimini temizleyip tekrar deneyin.',
        sourceLabel: 'İzmir Açık Veri Portali • Taksi Duraklar',
        sourceUrl: 'https://openapi.izmir.bel.tr/api/ibb/cbs/taksi-duraklar',
        loadPoints: loadTaxiStands,
    },
    {
        id: 'tren-garlari',
        title: 'Tren Garları',
        category: 'Ulaşım',
        description: 'İzmir genelindeki tren garlarını harita üzerinde görüntüleyin.',
        searchPlaceholder: 'Tren gari, ilçe veya mahalle ara...',
        emptyStateTitle: 'Tren gari bulunamadi',
        emptyStateDescription: 'Arama terimini temizleyip tekrar deneyin.',
        sourceLabel: 'İzmir Açık Veri Portali • Tren Garlarıi',
        sourceUrl: 'https://openapi.izmir.bel.tr/api/ibb/cbs/tren-garlari',
        loadPoints: loadTrainStations,
    },
    {
        id: 'vapur-iskeleleri',
        title: 'Vapur İskeleleri',
        category: 'Ulaşım',
        description: 'İzmir genelindeki vapur iskeleleri konumlarını harita üzerinde görüntüleyin.',
        searchPlaceholder: 'Iskele, ilçe veya mahalle ara...',
        emptyStateTitle: 'Iskele bulunamadi',
        emptyStateDescription: 'Arama terimini temizleyip tekrar deneyin.',
        sourceLabel: 'İzmir Açık Veri Portali • Vapur İskeleleri',
        sourceUrl: 'https://openapi.izmir.bel.tr/api/ibb/cbs/vapur-iskeleleri',
        loadPoints: loadFerryPorts,
    },
    {
        id: 'muhtarliklar',
        title: 'Muhtarlıklar',
        category: 'Yönetim',
        description: 'İzmir genelindeki muhtarlık konumlarını harita üzerinde görüntüleyin.',
        searchPlaceholder: 'Muhtarlik, ilçe veya mahalle ara...',
        emptyStateTitle: 'Muhtarlik bulunamadi',
        emptyStateDescription: 'Arama terimini temizleyip tekrar deneyin.',
        sourceLabel: 'İzmir Açık Veri Portali • Muhtarliklar',
        sourceUrl: 'https://openapi.izmir.bel.tr/api/ibb/cbs/muhtarliklar',
        loadPoints: loadMuhtarliklar,
    },
    {
        id: 'plajlar',
        title: 'Plajlar',
        category: 'Rekreasyon',
        description: 'İzmir genelindeki plajları harita üzerinde görüntüleyin.',
        searchPlaceholder: 'Plaj, ilçe veya mahalle ara...',
        emptyStateTitle: 'Plaj bulunamadi',
        emptyStateDescription: 'Arama terimini temizleyip tekrar deneyin.',
        sourceLabel: 'İzmir Açık Veri Portali • Plajlar',
        sourceUrl: 'https://openapi.izmir.bel.tr/api/ibb/cbs/plajlar',
        loadPoints: loadBeaches,
    },
    {
        id: 'hamamlar',
        title: 'Hamamlar',
        category: 'Rekreasyon',
        description: 'İzmir genelindeki hamamları harita üzerinde görüntüleyin.',
        searchPlaceholder: 'Hamam, ilçe veya mahalle ara...',
        emptyStateTitle: 'Hamam bulunamadi',
        emptyStateDescription: 'Arama terimini temizleyip tekrar deneyin.',
        sourceLabel: 'İzmir Açık Veri Portali • Hamamlar',
        sourceUrl: 'https://openapi.izmir.bel.tr/api/ibb/cbs/hamamlar',
        loadPoints: loadBaths,
    },
    {
        id: 'kaplicalar',
        title: 'Kaplıcalar',
        category: 'Rekreasyon',
        description: 'İzmir genelindeki kaplıca alanlarını harita üzerinde görüntüleyin.',
        searchPlaceholder: 'Kaplıcalar, ilçe veya mahalle ara...',
        emptyStateTitle: 'Kaplıcalar bulunamadi',
        emptyStateDescription: 'Arama terimini temizleyip tekrar deneyin.',
        sourceLabel: 'İzmir Açık Veri Portali • Kaplıcalar',
        sourceUrl: 'https://openapi.izmir.bel.tr/api/ibb/cbs/kaplicalar',
        loadPoints: loadSpringResorts,
    },
    {
        id: 'fuar-alanlari',
        title: 'Fuar Alanları',
        category: 'Rekreasyon',
        description: 'İzmir genelindeki fuar alanlarını harita üzerinde görüntüleyin.',
        searchPlaceholder: 'Fuar, ilçe veya mahalle ara...',
        emptyStateTitle: 'Fuar bulunamadi',
        emptyStateDescription: 'Arama terimini temizleyip tekrar deneyin.',
        sourceLabel: 'İzmir Açık Veri Portali • Fuar Alanları',
        sourceUrl: 'https://openapi.izmir.bel.tr/api/ibb/cbs/fuar-alanlari',
        loadPoints: loadFairs,
    },
    {
        id: 'kutuphaneler',
        title: 'Kütüphaneler',
        category: 'Kültür',
        description: 'İzmir genelindeki kütüphaneleri harita üzerinde görüntüleyin.',
        searchPlaceholder: 'Kutuphane, ilçe veya mahalle ara...',
        emptyStateTitle: 'Kutuphane bulunamadi',
        emptyStateDescription: 'Arama terimini temizleyip tekrar deneyin.',
        sourceLabel: 'İzmir Açık Veri Portali • Kütüphaneler',
        sourceUrl: 'https://openapi.izmir.bel.tr/api/ibb/cbs/kutuphaneler',
        loadPoints: loadLibraries,
    },
    {
        id: 'kultur-merkezleri',
        title: 'Kültür Merkezleri',
        category: 'Kültür',
        description: 'İzmir genelindeki kultur merkezlerini harita üzerinde görüntüleyin.',
        searchPlaceholder: 'Kültür merkezi, ilçe veya mahalle ara...',
        emptyStateTitle: 'Kültür merkezi bulunamadi',
        emptyStateDescription: 'Arama terimini temizleyip tekrar deneyin.',
        sourceLabel: 'İzmir Açık Veri Portali • Kültür Merkezleri',
        sourceUrl: 'https://openapi.izmir.bel.tr/api/ibb/cbs/kultur-merkezleri',
        loadPoints: loadCulturalCenters,
    },
    {
        id: 'opera-bale',
        title: 'Opera ve Bale',
        category: 'Kültür',
        description: 'Izmir\'deki opera ve bale mekanlarını harita üzerinde görüntüleyin.',
        searchPlaceholder: 'Opera, bale, ilçe veya mahalle ara...',
        emptyStateTitle: 'Opera bale mekanı bulunamadi',
        emptyStateDescription: 'Arama terimini temizleyip tekrar deneyin.',
        sourceLabel: 'İzmir Açık Veri Portali • Opera ve Bale',
        sourceUrl: 'https://openapi.izmir.bel.tr/api/ibb/cbs/opera-bale',
        loadPoints: loadOperaAndBallet,
    },
    {
        id: 'galeriler-salonlar',
        title: 'Galeriler ve Salonlar',
        category: 'Kültür',
        description: 'Izmir\'deki sanat galeri ve sergi salonlarını harita üzerinde görüntüleyin.',
        searchPlaceholder: 'Galeri, salon, ilçe veya mahalle ara...',
        emptyStateTitle: 'Galeri bulunamadi',
        emptyStateDescription: 'Arama terimini temizleyip tekrar deneyin.',
        sourceLabel: 'İzmir Açık Veri Portali • Galeriler ve Salonlar',
        sourceUrl: 'https://openapi.izmir.bel.tr/api/ibb/cbs/galeriler-salonlar',
        loadPoints: loadGalleriesAndHalls,
    },
    {
        id: 'senfoni-orkestrasi',
        title: 'Senfoni Orkestrası',
        category: 'Kültür',
        description: 'Izmir\'deki senfoni orkestrası mekanlarını harita üzerinde görüntüleyin.',
        searchPlaceholder: 'Senfoni, orkestrası, ilçe veya mahalle ara...',
        emptyStateTitle: 'Senfoni mekanı bulunamadi',
        emptyStateDescription: 'Arama terimini temizleyip tekrar deneyin.',
        sourceLabel: 'İzmir Açık Veri Portali • Senfoni Orkestrası',
        sourceUrl: 'https://openapi.izmir.bel.tr/api/ibb/cbs/senfoni-orkestrasi',
        loadPoints: loadPhilharmonic,
    },
    {
        id: 'sinemalar',
        title: 'Sinemalar',
        category: 'Kültür',
        description: 'İzmir genelindeki sinemaları harita üzerinde görüntüleyin.',
        searchPlaceholder: 'Sinema, ilçe veya mahalle ara...',
        emptyStateTitle: 'Sinema bulunamadi',
        emptyStateDescription: 'Arama terimini temizleyip tekrar deneyin.',
        sourceLabel: 'İzmir Açık Veri Portali • Sinemalar',
        sourceUrl: 'https://openapi.izmir.bel.tr/api/ibb/cbs/sinemalar',
        loadPoints: loadCinemas,
    },
    {
        id: 'tiyatrolar',
        title: 'Tiyatrolar',
        category: 'Kültür',
        description: 'İzmir genelindeki tiyatroları harita üzerinde görüntüleyin.',
        searchPlaceholder: 'Tiyatro, ilçe veya mahalle ara...',
        emptyStateTitle: 'Tiyatro bulunamadi',
        emptyStateDescription: 'Arama terimini temizleyip tekrar deneyin.',
        sourceLabel: 'İzmir Açık Veri Portali • Tiyatrolar',
        sourceUrl: 'https://openapi.izmir.bel.tr/api/ibb/cbs/tiyatrolar',
        loadPoints: loadTheaters,
    },
    {
        id: 'muzeler',
        title: 'Müzeler',
        category: 'Kültür',
        description: 'İzmir genelindeki müzeleri harita üzerinde görüntüleyin.',
        searchPlaceholder: 'Müzeler, ilçe veya mahalle ara...',
        emptyStateTitle: 'Müzeler bulunamadi',
        emptyStateDescription: 'Arama terimini temizleyip tekrar deneyin.',
        sourceLabel: 'İzmir Açık Veri Portali • Müzeler',
        sourceUrl: 'https://openapi.izmir.bel.tr/api/ibb/cbs/muzeler',
        loadPoints: loadMuseums,
    },
    {
        id: 'antik-kentler',
        title: 'Antik Kentler',
        category: 'Tarih',
        description: 'İzmir genelindeki antik kentleri harita üzerinde görüntüleyin.',
        searchPlaceholder: 'Antik kent, ilçe veya mahalle ara...',
        emptyStateTitle: 'Antik kent bulunamadi',
        emptyStateDescription: 'Arama terimini temizleyip tekrar deneyin.',
        sourceLabel: 'İzmir Açık Veri Portali • Antik Kentler',
        sourceUrl: 'https://openapi.izmir.bel.tr/api/ibb/cbs/antik-kentler',
        loadPoints: loadAncientCities,
    },
    {
        id: 'antik-yapılar',
        title: 'Antik Yapılar',
        category: 'Tarih',
        description: 'Izmir\'deki antik kent yapılarını harita üzerinde görüntüleyin.',
        searchPlaceholder: 'Antik yapı, ilçe veya mahalle ara...',
        emptyStateTitle: 'Antik yapı bulunamadi',
        emptyStateDescription: 'Arama terimini temizleyip tekrar deneyin.',
        sourceLabel: 'İzmir Açık Veri Portali • Antik Yapılar',
        sourceUrl: 'https://openapi.izmir.bel.tr/api/ibb/cbs/antik-yapılar',
        loadPoints: loadAncientCityStructures,
    },
    {
        id: 'kosk-konaklar',
        title: 'Köşk ve Konaklar',
        category: 'Tarih',
        description: 'Izmir\'deki tarihi köşk ve konakları harita üzerinde görüntüleyin.',
        searchPlaceholder: 'Köşk, konak, ilçe veya mahalle ara...',
        emptyStateTitle: 'Köşk veya konak bulunamadi',
        emptyStateDescription: 'Arama terimini temizleyip tekrar deneyin.',
        sourceLabel: 'İzmir Açık Veri Portali • Köşk ve Konaklar',
        sourceUrl: 'https://openapi.izmir.bel.tr/api/ibb/cbs/kosk-konaklar',
        loadPoints: loadMansionsAndManors,
    },
    {
        id: 'kule-anıt-heykeller',
        title: 'Kule, Anıt ve Heykeller',
        category: 'Tarih',
        description: 'Izmir\'deki tarihi kule, anıt ve heykelleri harita üzerinde görüntüleyin.',
        searchPlaceholder: 'Kule, anıt, heykel, ilçe veya mahalle ara...',
        emptyStateTitle: 'Kule, anıt veya heykel bulunamadi',
        emptyStateDescription: 'Arama terimini temizleyip tekrar deneyin.',
        sourceLabel: 'İzmir Açık Veri Portali • Kule Anit Heykeller',
        sourceUrl: 'https://openapi.izmir.bel.tr/api/ibb/cbs/kule-anıt-heykeller',
        loadPoints: loadTowersMonumentsStatues,
    },
    {
        id: 'tarihi-carsi-hanlar',
        title: 'Tarihi Çarşı ve Hanlar',
        category: 'Tarih',
        description: 'Izmir\'deki tarihi çarşı ve hanları harita üzerinde görüntüleyin.',
        searchPlaceholder: 'Çarşı, han, ilçe veya mahalle ara...',
        emptyStateTitle: 'Çarşı veya han bulunamadi',
        emptyStateDescription: 'Arama terimini temizleyip tekrar deneyin.',
        sourceLabel: 'İzmir Açık Veri Portali • Tarihi Çarşı ve Hanlar',
        sourceUrl: 'https://openapi.izmir.bel.tr/api/ibb/cbs/tarihi-carsi-hanlar',
        loadPoints: loadHistoricMarketAndCaravansaries,
    },
    {
        id: 'tarihi-su-yapilari',
        title: 'Tarihi Su Yapıları',
        category: 'Tarih',
        description: 'Izmir\'deki tarihi su yapılarını harita üzerinde görüntüleyin.',
        searchPlaceholder: 'Su yapisi, ilçe veya mahalle ara...',
        emptyStateTitle: 'Su yapisi bulunamadi',
        emptyStateDescription: 'Arama terimini temizleyip tekrar deneyin.',
        sourceLabel: 'İzmir Açık Veri Portali • Tarihi Su Yapıları',
        sourceUrl: 'https://openapi.izmir.bel.tr/api/ibb/cbs/tarihi-su-yapilari',
        loadPoints: loadHistoricWaterStructures,
    },
    {
        id: 'tarihi-yapılar',
        title: 'Tarihi Yapılar',
        category: 'Tarih',
        description: 'İzmir genelindeki tarihi yapıları harita üzerinde görüntüleyin.',
        searchPlaceholder: 'Tarihi yapı, ilçe veya mahalle ara...',
        emptyStateTitle: 'Tarihi yapı bulunamadi',
        emptyStateDescription: 'Arama terimini temizleyip tekrar deneyin.',
        sourceLabel: 'İzmir Açık Veri Portali • Tarihi Yapılar',
        sourceUrl: 'https://openapi.izmir.bel.tr/api/ibb/cbs/tarihi-yapılar',
        loadPoints: loadHistoricStructures,
    },
];

export const defaultMapId = mapRegistry[0].id;

export const getMapDefinitionById = (mapId: string | null) => {
    if (!mapId) {
        return mapRegistry[0];
    }

    return mapRegistry.find((map) => map.id === mapId) ?? mapRegistry[0];
};
